### ISSUE TITLE
Define and document procedure for deployments

### ISSUE THREAD

**Issue by pablotolosa-aircury** [elemwave/website#12]
An extra rule could be added to require a successful deployment in a preview environment before merging the PR.

**Comment by pablotolosa-aircury** [comment]
Here is the documentation for a web deployment using GitHub pages
https://docs.google.com/document/d/1fnoa_vqkArMwBE3iNd6Wd-HRWb22aIODHQroAP3ktbE/edit?usp=sharing

**Comment by cristobaldiaz-aircury** [comment]
This could be added as part of the repository in a .md

**Comment by pablotolosa-aircury** [comment]
I added the deployment documentation in a .md file  https://github.com/elemwave/website/pull/15

**Comment by pablotolosa-aircury** [comment]
Re-edited the documentation with suggested changes #15

**Comment by pablotolosa-aircury** [comment]
The last commit on #17 has the suggested changes

**Comment by pablotolosa-aircury** [comment]
#21 Added the documentation with the suggested changes
