### ISSUE TITLE
Search a solution for the rest of vulnerabilities

### ISSUE THREAD

**Issue by pablotolosa-aircury** [elemwave/website#19]
Nokogiri need to get updated in order to fix 11 security problems  #8

**Comment by cristobaldiaz-aircury** [comment]
I see there's another card for this: https://github.com/elemwave/website/issues/18. Is this issue duplicated?

**Comment by pablotolosa-aircury** [comment]
No, this one was about the nokogiri update pull request that was sent by the dependanbot to fix some security problems. I fixed the rest of  problems but 11 of them are involved with the nokogiri version.

**Comment by pablotolosa-aircury** [comment]
Using the bundle-audit gem to search vulnerabilities of our project only shows us that the "commonmarker" gem version is the one that is causing troubles. I think we should try to update that one first and check if the security problems are solved then.

**Comment by cristobaldiaz-aircury** [comment]
Issue duplicated by https://github.com/elemwave/website/issues/29
