### ISSUE TITLE
Design document proposals

### ISSUE THREAD

**Issue by cristobaldiaz-aircury** [elemwave/website#42]
Design and improves proposals.
https://docs.google.com/document/d/1qcdtmKYksn-p-cJIOo3X29y05wyz8s9BC8Eq30lshJ4/edit?usp=sharing

**Comment by cristobaldiaz-aircury** [comment]
Missing tickets for:
1. Change the copyright year automatically.
2. Addition of a button to get back to the top.
3. Try a different a font for the titles.

**Comment by juanjoseortega-aircury** [comment]
> Missing tickets for:
> 
> 1. Change the copyright year automatically.
> 2. Addition of a button to get back to the top.
> 3. Try a different a font for the titles.

Added at ticket #43
